* Decentralized Storage Platforms

** Contents 								:TOC:
- [[#decentralized-storage-platforms][Decentralized Storage Platforms]]
  - [[#overview][Overview]]
  - [[#platforms][Platforms]]

** Overview

This document is intended to list projects implementing decentralized storage systems (I'm calling them "platforms" for want of a better term).

Initially the list will be just that --- a list of names and urls --- but I intend to go through and provide a brief technical summary of each project (with references).  I am not going to say "X is better than Y" but I will pose questions if only to encapsulate and bookmark gaps in my own understanding.  I'll also focus on the tech, with less discussion of the financial side (I mean things like VC backing, market cap, etc.).

I would like the document to be comprehensive, or at least “representative”. If I have missed a relevant project, please let me know through the usual channels (issues, forks, PRs, tweets, emails, etc.).

Thank you.

One disclaimer: from July 2018 to December 2019 I was a Senior Erlang Developer at Arweave, one of the projects below.

** Platforms

- for each:
  - link to home page
  - link to white paper or equivalent
  - brief description
  - highlight unique/innovative/different contributions
  - query bits I don't understand
  - note most recent activity

*** IPFS & related
**** IPFS

- https://ipfs.io/
- [[https://twitter.com/IPFSbot][@IPFSbot]]

***** Hosted IPFS

Several projects offer hosted wrappers around IPFS for improved ease of use and/or reliability.  Some examples as I come across them:

- [[https://pinata.cloud/][IPFS Pinata]]: [[https://twitter.com/IPFSPinata][@IPFSPinata]]
- [[https://temporal.cloud/][Temporal]]: [[https://twitter.com/Temporalcloud][@Temporalcloud]]

**** Filecoin

- https://filecoin.io
- [[https://twitter.com/MineFilecoin][@MineFilecoin]]

- "Mainnet launch window: March 23 - April 24, 2020" [[https://filecoin.io/blog/roadmap-update-2019-q4/][(Filecoin Roadmap Update Q4 2019]])

**** BTFS (BitTorrent File System)

- https://www.bittorrent.com/btfs/
- [[https://twitter.com/BitTorrent][@BitTorrent]]

"BTFS is a fork of IPFS ... integrated with the TRON blockchain" (from the [[https://www.bittorrent.com/btfs/faq/][faq]]).

- Why is BTFS a fork of IPFS?  What does IPFS provide that BitTorrent doesn't already have?

**** Decent

- https://decent.ch/
- [[https://twitter.com/DECENTplatform][@DECENTplatform]]

- "With native integration of file sharing system IPFS and CDN, DCore enables large file storage and distribution." ([[https://decent.ch/dcore/][DCore]]).
- [[https://docs.decent.ch/DCoreTechDesc/index.html][DCore IPFS Layer]]

**** Peergos

- https://peergos.org
- [[https://twitter.com/peergos][@peergos]]

Peergos uses IPFS for storage, i.e., each Peergos server "includes an instance of IPFS" [[[https://book.peergos.org/architecture/physical.html?highlight=ipfs][Architecture]]].

For more details see:

- https://peergos.org/technology
- https://book.peergos.org/

*** The rest
**** 0chain

- https://0chain.net/
- [[https://twitter.com/0Chain][@0Chain]]

**** Arweave

- https://www.arweave.org/
- [[https://twitter.com/arweaveteam][@arweaveteam]]

**** Dat

- https://dat.foundation/
- [[https://twitter.com/datfoundation][@datfoundation]]

**** Internxt

- https://internxt.com/
- [[https://twitter.com/Internxt][@Internxt]]

"All users recieve a free 2 GB storage plan to experience X Cloud. If you enjoy the service you can upgrade to our 20 GB plan for €0.89, 200 GB plan for €3.49 or alternativly [sic] upgrade to our largest plan 2 TB for €8.99." [charges monthly] [[https://internxt.com/cloud][(XCloud]])

"X Core is a simple, distributed, peer-to-peer downloadable application that enables anyone to act as a computing server called 'hosts' who rent out their computers extra hard-drive space which securely stores and shares encrypted shards of X Cloud user data for a return of our cryptocurrency token INXT." [[https://internxt.com/core][(XCore]])

Little/no detail on how storage is verified, but Internxt seems to be partly a javascript UI based on a Storj backend:

- "We forked Storj" 2019/06/11: https://bitcointalk.org/index.php?topic=5153073.0
- See also their github page: https://github.com/internxt

**** Maidsafe

- https://maidsafe.net
- [[https://twitter.com/maidsafe][@maidsafe]]

**** Opacity

- https://www.opacity.io/
- [[https://twitter.com/Opacity_Storage][@Opacity_Storage]]

Basic $39.99/year [[https://www.opacity.io/sign-up][(Sign up]])

**** RIF

- https://www.rifos.org/blog/rif-storage-a-decentralized-storage-solution/
- [[https://twitter.com/rif_os][@rif_os]]

**** Sharder

- https://www.sharder.org/
- [[https://twitter.com/SharderChain][@SharderChain]]

**** Sia

- https://sia.tech
- [[https://twitter.com/siatechhq][@siatechhq]]

**** Storj

- https://storj.io
- [[https://twitter.com/storjproject][@storjproject]]

**** Swarm

- https://swarm-guide.readthedocs.io/en/latest/index.html
- [[https://twitter.com/ethswarm][@ethswarm]]

